dist: trusty
sudo: false
language: node_js
node_js:
  - node
addons:
  firefox: latest-esr
cache:
  directories:
    - node_modules
before_script:
  - npm install polymer-cli
  - $(npm bin)/polymer lint
script: xvfb-run $(npm bin)/polymer test --module-resolution=node --npm -l firefox
