language: node_js
node_js:
- node
addons:
  firefox: latest
env:
  global:
  - MOZ_HEADLESS=1
before_script:
- npm run lint
script: npm run test -- -l firefox
deploy:
  provider: npm
  email: npm@dweimer.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: chadweimer/iron-star-rating
  edge: true
